// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var JsSerial$Base = require("./JsSerial.bs.js");

function init(device) {
  var port = JsSerial$Base.serial(device, undefined, /* () */0);
  var readline = JsSerial$Base.readline(port);
  readline.on("data", (function (line) {
            var port$1 = port;
            var msg = line.trim();
            console.log(">", msg);
            var tmp = msg === "[MSG:'$H'|'$X' to unlock]" ? "$X" : undefined;
            return JsSerial$Base.writeOption(port$1, tmp);
          })).on("close", (function (param) {
          console.log("port closed, exiting");
          return Process.exit(0);
        }));
  return port;
}

exports.init = init;
/* process Not a pure module */
