// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Process = require("process");
var JsSerial$Base = require("./JsSerial.bs.js");

var port = JsSerial$Base.serial("/dev/ttyUSB0", {
      baudRate: 115200
    }, /* () */0);

var readline = JsSerial$Base.readline(port);

function dispatch(port, msg) {
  console.log("> " + msg);
  var tmp = msg === "[MSG:'$H'|'$X' to unlock]" ? "$X" : undefined;
  return JsSerial$Base.writeOption(port, tmp);
}

readline.on("data", (function (line) {
          return dispatch(port, line.trim());
        })).on("close", (function (param) {
        console.log("port closed, exiting");
        return Process.exit(0);
      }));

exports.port = port;
exports.readline = readline;
exports.dispatch = dispatch;
/* port Not a pure module */
