// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Serialport = require("serialport");
var ParserReadline = require("@serialport/parser-readline");

function serial(device, configOpt, param) {
  var config = configOpt !== undefined ? configOpt : ({
        baudRate: 115200
      });
  return new Serialport(device, config);
}

function readline(port) {
  var rl = new ParserReadline();
  port.pipe(rl);
  return rl;
}

exports.serial = serial;
exports.readline = readline;
/* serialport Not a pure module */
