// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Serialport = require("serialport");

function createSerial(port, configOpt, param) {
  var config = configOpt !== undefined ? configOpt : ({
        baud: 6400
      });
  return new Serialport(port, config);
}

exports.createSerial = createSerial;
/* serialport Not a pure module */
