// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Rxjs = require("rxjs");
var Grbl$Base = require("./Grbl.bs.js");

function init(grbl) {
  return {
          grbl: grbl,
          painting: false,
          subject: new Rxjs.Subject()
        };
}

function paint(painter, state) {
  if (state) {
    Grbl$Base.send(painter.grbl, "M3 S1000");
    return painter;
  } else {
    Grbl$Base.send(painter.grbl, "M3 S0");
    return painter;
  }
}

exports.init = init;
exports.paint = paint;
/* rxjs Not a pure module */
