// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_module = require("bs-platform/lib/js/caml_module.js");

var $$Math = Caml_module.init_mod(/* tuple */[
      "ThreeOcaml.ml",
      16,
      6
    ], /* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Euler"
          ]]]));

Caml_module.update_mod(/* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Euler"
          ]]]), $$Math, $$Math);

var Camera = Caml_module.init_mod(/* tuple */[
      "ThreeOcaml.ml",
      49,
      6
    ], /* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Perspective"
          ]]]));

Caml_module.update_mod(/* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Perspective"
          ]]]), Camera, Camera);

var Geometry = Caml_module.init_mod(/* tuple */[
      "ThreeOcaml.ml",
      58,
      6
    ], /* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Box"
          ]]]));

Caml_module.update_mod(/* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "Box"
          ]]]), Geometry, Geometry);

var Material = Caml_module.init_mod(/* tuple */[
      "ThreeOcaml.ml",
      68,
      6
    ], /* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "MeshBasic"
          ]]]));

Caml_module.update_mod(/* Module */Block.__(0, [[/* tuple */[
            /* Module */Block.__(0, [[]]),
            "MeshBasic"
          ]]]), Material, Material);

var Vector3 = /* () */0;

var Vector2 = /* () */0;

var Mesh = /* () */0;

exports.$$Math = $$Math;
exports.Vector3 = Vector3;
exports.Vector2 = Vector2;
exports.Camera = Camera;
exports.Geometry = Geometry;
exports.Material = Material;
exports.Mesh = Mesh;
/* Math Not a pure module */
