// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Three = require("three");

function make(x, y) {
  return /* ThreeInstance */Block.__(1, [new Three.Vector2(x, y)]);
}

function ensureInstance(v) {
  if (v.tag) {
    return v[0];
  } else {
    return new Three.Vector2(v[0], v[1]);
  }
}

function ensureInstanceClone(v) {
  if (v.tag) {
    return v[0].clone();
  } else {
    return new Three.Vector2(v[0], v[1]);
  }
}

function add(v1, v2) {
  return ensureInstance(v1).add(ensureInstance(v2));
}

var Vector2 = {
  make: make,
  ensureInstance: ensureInstance,
  ensureInstanceClone: ensureInstanceClone,
  add: add
};

exports.Vector2 = Vector2;
/* three Not a pure module */
